name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        BUILDMODE: [CIBUILDWHEEL]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Set up QEMU
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.BUILDMODE == 'CIBUILDWHEEL' }}
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Build wheel
        if: ${{ matrix.BUILDMODE == 'CIBUILDWHEEL' }}
        env:
          CIBW_BEFORE_ALL: "echo Testing; pwd; ls"
          CIBW_SKIP: pp* *-musllinux*
          CIBW_ARCHS_LINUX: aarch64
        run: |
          python -m pip install cibuildwheel
          cibuildwheel --output-dir wheelhouse
